import type { Book } from "./types";
const entries = [
  [
    "slow-mornings",
    "ধীর সকালের গল্প",
    "The Art of Slow Mornings",
    "জীবনযাপন",
    "Lifestyle",
    "lifestyle",
    "forest",
    24900,
    128,
  ],
  [
    "city-of-rain",
    "বৃষ্টির শহর",
    "A City Made of Rain",
    "গল্প ও উপন্যাস",
    "Fiction",
    "fiction",
    "blue",
    19900,
    184,
  ],
  [
    "small-beginnings",
    "ছোট শুরু, বড় স্বপ্ন",
    "Small Beginnings",
    "আত্মউন্নয়ন",
    "Personal growth",
    "growth",
    "orange",
    29900,
    156,
  ],
  [
    "creative-mind",
    "সৃজনশীল মন",
    "The Creative Mind",
    "সৃজনশীলতা",
    "Creativity",
    "creativity",
    "pink",
    24900,
    112,
  ],
  [
    "beyond-the-map",
    "মানচিত্রের বাইরে",
    "Beyond the Map",
    "ভ্রমণ",
    "Travel",
    "travel",
    "olive",
    17900,
    144,
  ],
  [
    "quiet-focus",
    "মনোযোগের শক্তি",
    "The Power of Quiet Focus",
    "আত্মউন্নয়ন",
    "Personal growth",
    "growth",
    "violet",
    27900,
    136,
  ],
  [
    "everyday-money",
    "সহজ টাকার হিসাব",
    "Everyday Money",
    "জীবনযাপন",
    "Lifestyle",
    "lifestyle",
    "yellow",
    22900,
    108,
  ],
  [
    "letters-to-tomorrow",
    "আগামীর কাছে চিঠি",
    "Letters to Tomorrow",
    "গল্প ও উপন্যাস",
    "Fiction",
    "fiction",
    "red",
    19900,
    96,
  ],
] as const;
export const demoBooks: Book[] = entries.map((e, i) => ({
  id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
  slug: e[0],
  title_bn: e[1],
  title_en: e[2],
  author_bn: "বইশেলফ সম্পাদকীয়",
  author_en: "BoiShelf Editorial",
  description_bn: `${e[1]} — নতুন ভাবনা আর পাঠের আনন্দ খুঁজে নেওয়ার একটি আমন্ত্রণ। এটি বইশেলফের নমুনা বই; দোকান ও ডাউনলোডের অভিজ্ঞতা দেখানোর জন্য তৈরি। কোনো বাস্তব লেখকের প্রকাশিত বই নয়।`,
  description_en: `${e[2]} is an invitation to discover a fresh perspective and the joy of a good read. This is an original BoiShelf sample used to demonstrate the store and download experience, not a published work by a real author.`,
  category: e[5],
  cover_style: e[6],
  price_paisa: e[7],
  pages: e[8],
  language: "bn",
  cover_path: null,
  formats: ["PDF", "EPUB"],
  published: true,
  is_demo: true,
  featured: i < 3,
  archived_at: null,
  preview_pages: 0,
}));
export const categories = [
  { id: "all", bn: "সব বই", en: "All books" },
  { id: "fiction", bn: "গল্প ও উপন্যাস", en: "Fiction" },
  { id: "growth", bn: "আত্মউন্নয়ন", en: "Personal growth" },
  { id: "lifestyle", bn: "জীবনযাপন", en: "Lifestyle" },
  { id: "creativity", bn: "সৃজনশীলতা", en: "Creativity" },
  { id: "travel", bn: "ভ্রমণ", en: "Travel" },
];
